### ISSUE TITLE
Integration - icon path goes blank, etc

### ISSUE THREAD

**Issue by IanAdd** [thomasloven/hass-favicon#10]
1) The icon path keeps going blank, not worked out the sequence to have it happen yet.
I have found icon path blank and also reset to default /local/favicon/

2) I set the icon path (/local/favicons/red/) click save, refresh the page and the icon (on chrome) tab goes red.
I then go back and change the name and click save, refresh the page, no name change.
I go back again, change the icon path (by removing the last character and replacing it), click save and refresh and the name changes.

I open a new tab and then open the same HA as is currently open and coloured... It opens in standard blue with no custom name. Check the integration values, look good, cancel out. Hit refresh and the name and icon change to correct values. NOT reliably repeatable.

I have found icon path reverting to blank and also reset to default /local/favicon/

I cannot find a definitive sequence to make it lose these settings. But something is wrong with the 'save' process regardless.

**Comment by thomasloven** [comment]
Are you mixing the two configuration methods?

**Comment by IanAdd** [comment]
Sorry, not sure what you mean by two methods ? Are you referring to compact_header vs favicon or something else?
Item 2 looks simply like a bit of code checks if the icon path has been touched and saves everything if it has, but does nothing if it hasn't.

**Comment by thomasloven** [comment]
No, I mean have you added `favicon:` to configuration.yaml, but are still trying to configure it from the integrations page?

**Comment by IanAdd** [comment]
no mention of favicon in configuration.yaml

**Comment by IanAdd** [comment]
Correction, the system that I spotted going back to a default of /local/favicon/ did exist in configuration.yaml.
So I have three systems, two had it in config, one didn't.
Hold fire whilst I reboot the two confused ones and let's see what I end up with.
Thanks for the clue.

**Comment by IanAdd** [comment]
Ok, booted all three systems. Sticking with the one that never had favicon: in config is doing this:
Pick a link to open HA - it comes up with correct name and red icon.
Then chose configuration edit to check again that there is no favicon.
Right clicked chrome tab and picked duplicate and new tab comes up blue icon
Looked in integrations - details are still there

**Comment by IanAdd** [comment]
As the tab opens it starts with the red icon and my defined text in the tab and this reverts to the standard icon and title as the page load completes. The favicon defined title is shown ok within the HA web page.
