### ISSUE TITLE
0.109 throws this up

### ISSUE THREAD

**Issue by IanAdd** [thomasloven/hass-favicon#12]
Log Details (WARNING)
Logger: homeassistant.helpers.translation
Source: helpers/translation.py:206
First occurred: 8:16:57 PM (2 occurrences)
Last logged: 8:16:59 PM

favicon: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this

**Comment by vMeph** [comment]
same here
