### ISSUE TITLE
Can't add Integration with New Update

### ISSUE THREAD

**Issue by ttaidapos** [thomasloven/hass-favicon#13]
Installs fine but when trying to add in integration no Help Text is displayed

![image](https://user-images.githubusercontent.com/27898709/80840376-c9931f80-8bc2-11ea-951c-d573edfc5f8c.png)

**Comment by thomasloven** [comment]
Home assistant version?

**Comment by ttaidapos** [comment]
108.x

**Comment by thomasloven** [comment]
Then you need to use release 7 or upgrade to 0.109.
