### ISSUE TITLE
Gui page title no longer set in 117.X and now 118

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/hass-favicon#14]
is this now defunct with the new smaller header in HA 117.x? Or can we still set it somehow to show the instance name in the page title.
thanks for having a look

**Comment by Mariusthvdb** [comment]
somehow updating to 117.0b1 removed the favicon folder that was set before in the instance and the integration was not configured in the UI anylonger (or vice versa )

After having re-installed the favicon integration, all seems well again, so closing this.
Sorry for any confusion this may have caused.

**Comment by Mariusthvdb** [comment]
please allow me to reiterate on this. 118 finally broke it completely. No more instance name in the left side menu title, only Homeassistant.

**Comment by moshiko2312** [comment]
me to :-( 
118 finally broke it completely. No more instance name in the left side menu title, only Homeassistant. :-(

**Comment by thomasloven** [comment]
Fixed in 10.2
