### ISSUE TITLE
No 'Favicon' integration shows up / HA 116.4

### ISSUE THREAD

**Issue by Liese2007** [thomasloven/hass-favicon#15]
Hi,
I just setup a new system with only HACS as additional integration.
I added the 

> translations folder
> __init__.py
> config_flow.py
> manifest.json

to
 
my `custom_components/favicon` .

I also added at `configuration.yaml` following:

```
favicon:
  title: My Home
  icon_path: /local/favicons/
```

Some icons are in my icon folder `\config\www\favicons`.

After restart of HA I wanted to add the integration via GUI  - but it doesn't show up.
No icons can be seen.
My icons available are a bunch from [https://favicomatic.com/](https://favicomatic.com/).

Any idea, what might be wrong?

Regards
Joerg from Hamburg

**Comment by thomasloven** [comment]
You do not need to add anything to configuration.yaml if you intend to use the GUI to add the integration.

**Comment by SAOPP** [comment]
> You do not need to add anything to configuration.yaml if you intend to use the GUI to add the integration.

To be honest, I don’t understand a little, in the integration settings I don’t find a favicon, in hacs it is also missing, in the end, how to add the integration now on the latest core? Just add lines to the config?
