### ISSUE TITLE
Bug. Missing "Done" button in 0.117.0 when reordering sidebar 

### ISSUE THREAD

**Issue by bessarabov** [thomasloven/hass-favicon#17]
This is screenshot from 0.117.0 — After pressing the "Edit" button there is no "Done" button. And the only way to stop editing is to refresh the page:

![1](https://user-images.githubusercontent.com/47263/97801761-09a98c80-1c50-11eb-9092-557009a2e48e.png)

But after removing favicon custom component from Home Assistant there is a `Done` button:

![2](https://user-images.githubusercontent.com/47263/97801762-0dd5aa00-1c50-11eb-8761-2df9dd86addd.png)

PS At first I've created this issue in HA frontend issue https://github.com/home-assistant/frontend/issues/7522

**Comment by thomasloven** [comment]
Cannot reproduce.
Please make sure you are using the latest version of hass_favicon since this issue was solved for 0.115 in release 10.1.

**Comment by bessarabov** [comment]
Thank you! Yes, you are right, with the latest version of hass-favicon everything is woking fine.

I'm sorry for opening this issue without testing the latest version.
