### ISSUE TITLE
failed to setup on 2021.5.0

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/hass-favicon#20]
you are probably aware, but just in case...

<img width="298" alt="Schermafbeelding 2021-04-29 om 08 41 38" src="https://user-images.githubusercontent.com/33354141/116511457-c3637c00-a8c6-11eb-9885-c931797c0df3.png">

<img width="827" alt="Schermafbeelding 2021-04-29 om 08 40 25" src="https://user-images.githubusercontent.com/33354141/116511382-a75fda80-a8c6-11eb-9ec6-390f64787541.png">

**Comment by thomasloven** [comment]
Should be fixed with 10.4

**Comment by Mariusthvdb** [comment]
can confirm it is fixed!
thanks for the quick fix indeed.
