### ISSUE TITLE
Icon on login screen

### ISSUE THREAD

**Issue by sanderlv** [thomasloven/hass-favicon#23]
Hi Thomas, is it possible to change the icon & name of the login screen? So that I see when I login directly?

![image](https://user-images.githubusercontent.com/16528916/125208950-f8f8ee00-e295-11eb-99e0-31e27b24956e.png)

![image](https://user-images.githubusercontent.com/16528916/125208968-0a41fa80-e296-11eb-94ac-c331f72d97dd.png)

**Comment by thomasloven** [comment]
Nope.

This is by design - I don't want to mess with the login screen for security reasons.

Some of the methods described [here](https://github.com/thomasloven/hass-config/wiki/Changing-the-Home-Assistant-favicon) **may** work, though.

**Comment by sanderlv** [comment]
You do not happen to know how to that on a synology reverse proxy already proxying succesfully with websocket toy homeassistant?

**Comment by sanderlv** [comment]
Thomas, I found the location of the config in nginx

```
    location / {

        if ($proxy_x_forwarded_proto = false) {
            set $proxy_x_forwarded_proto '';
        }

        proxy_connect_timeout 60;

        proxy_read_timeout 60;

        proxy_send_timeout 60;

        proxy_intercept_errors off;

        proxy_http_version 1.1;

        proxy_set_header        Upgrade            $http_upgrade;

        proxy_set_header        Connection            $connection_upgrade;

        proxy_set_header        X-Real-IP            $remote_addr;

        proxy_set_header        X-Forwarded-For            $proxy_add_x_forwarded_for;

        proxy_set_header        X-Forwarded-Proto            $proxy_x_forwarded_proto;

        proxy_set_header        Host            $http_host;

        proxy_pass http://10.37.94.201:80;
```

I am struggling to get this in on the correct way as I am not experiences with this type of coding.

  location /static/icons/ {
    proxy_pass http://your_local_ha_ip:8123/local/icons/;
    ... # according to your needs e.g. proxy headers, redirects from http to https and such
  }
