### ISSUE TITLE
Is folder favicon or favicons

### ISSUE THREAD

**Issue by alexruffell** [thomasloven/hass-favicon#25]
The instructions refer to the folder as both favicon and favicons in different places. Which one is the correct spelling?

Also, when I used the integration to populate the name and icon path, I did not see a new entry in configuration.yaml . Should we be adding the entry as shown in the instructions AND also using the integration configuration to re-enter the same information?

**Comment by thomasloven** [comment]
When it says `favicon` it's `favicon`. When it says `favicons` it's `favicons`.

No. Those are two different methods. Pick one.
