### ISSUE TITLE
is this supposed to work with docker version too?

### ISSUE THREAD

**Issue by part-time-githubber** [thomasloven/hass-favicon#26]
i am using 

`ghcr.io/home-assistant/raspberrypi4-homeassistant   stable    03c62a68e12e   2 weeks ago   1.05GB`

and nothing in docker debug logs to suggest it attempted as following returns empty

`docker logs homeassistant 2>&1 | grep --color favicon`

**Comment by thomasloven** [comment]
Yes. I run docker.
