### ISSUE TITLE
doesn't work icons

### ISSUE THREAD

**Issue by milandzuris** [thomasloven/hass-favicon#27]
I set the icon and it doesn't work, I restarted HA and cleared the cache, and it still doesn't work.
![image](https://user-images.githubusercontent.com/42905545/147602088-452c4d8e-2823-4d94-a929-d340cbb1cfb7.png)
![image](https://user-images.githubusercontent.com/42905545/147602115-b773f326-e7e2-4b88-83e1-fa0992d0bdd3.png)
![image](https://user-images.githubusercontent.com/42905545/147602138-5e0684cf-0ea5-4969-ae16-b8008eb6ae4a.png)
![image](https://user-images.githubusercontent.com/42905545/147602158-cbe6b762-3c45-43aa-b8d6-80377991fa2a.png)

**Comment by thomasloven** [comment]
The Icon path is the directory in which you put the icons.

**Comment by milandzuris** [comment]
on PC working thank you so much, on phone i dont see new icon and name, what am I doing wrong?.

**Comment by milandzuris** [comment]
![image](https://user-images.githubusercontent.com/42905545/147676151-beecd59d-993b-4217-8312-9c2a4186dc58.png)

**Comment by thomasloven** [comment]
The Home Assistant companion app can change its icon from the settings - at least for iOS.
If you use a saved web app thing, I think you need to have the icons working before you save it.
