### ISSUE TITLE
the icon is not changing "for real"

### ISSUE THREAD

**Issue by niccolobusato** [thomasloven/hass-favicon#3]
![screen-record](https://user-images.githubusercontent.com/44100360/65149475-73ea7800-da22-11e9-8a53-7e01e49b89d4.gif)

This is my problem, i have installed your plugin via hacs with the integration method

i've cleared the cache!

**Comment by thomasloven** [comment]
Do you also have this installed? https://github.com/custom-cards/favicon-counter

**Comment by niccolobusato** [comment]
no i don't. but the issue was fixed by using the "configuration.yaml" method of installation.

**Comment by thomasloven** [comment]
That's very odd. Thanks for reporting!

**Comment by niccolobusato** [comment]
Thank you for your work :)
