### ISSUE TITLE
myne favicon doesnt change or load

### ISSUE THREAD

**Issue by IIIdefconIII** [thomasloven/hass-favicon#32]
hi my favicon doesnt change i followed the instructions, reset whole chrome but it doesnt update.

in you example ur using /local/favicons/green
tithout any extention i tried offcrouse my own picture SkyNet.png + SkyNet.ico
both are not working. restarted hass 2 times, ctrl +R and CTRl F+5 and deleted all chome stuff everal times.

Can you help me out for 20 coffees?

Im on latest versions on everything i run

**Comment by thomasloven** [comment]
I do not do this for money or donations. If I did I would have to file taxes for it, and I really don't want to go through the bother. Please use your money for [something better](https://account.nabucasa.com/signup/).

The path shall be for the directory in which the icons reside. The icon files need to be named as described in the readme.

**Comment by IIIdefconIII** [comment]
Ok thanks ill tet that icon name thing the path is ok/local/favicons/myname.png an myname.jico didn't work ill try thr names in you example but in the image you provider the name isn't the same as in the gif..


Met vriendelijke groet,

________________________ _______________________
Thomas van Dalen

E: ***@***.******@***.***>

T: +316 30 929 009

________________________________

**Comment by IIIdefconIII** [comment]
![image](https://github.com/thomasloven/hass-favicon/assets/9917659/ec65c8d0-9255-4bad-92dd-e4f54fdda00e)
restarting now will update soon

**Comment by IIIdefconIII** [comment]
nope restarted home assisnt, will reboot the servet tomorrow + change 
![image](https://github.com/thomasloven/hass-favicon/assets/9917659/703cc981-1eef-48a5-99ae-994944bc9d9a)
the titlle to SkyNetnew to test if thats even loading.

![image](https://github.com/thomasloven/hass-favicon/assets/9917659/1ee8845f-40d2-4fd0-b664-314c4e620368)

**Comment by IIIdefconIII** [comment]
Intel:

![image](https://github.com/thomasloven/hass-favicon/assets/9917659/853454dc-44c8-45f9-992d-9c6ee72d2991)

**Comment by IIIdefconIII** [comment]
More intel:

![image](https://github.com/thomasloven/hass-favicon/assets/9917659/ab848d0f-0ba6-4378-a522-033941c47c6e)

I redownloaded the latest 10.4 just to make sure

**Comment by IIIdefconIII** [comment]
i update the name to SkyNetNew and didnt apply
![image](https://github.com/thomasloven/hass-favicon/assets/9917659/bc75ca8b-b5ec-47d0-ab62-13442383577b)

**Comment by IIIdefconIII** [comment]
![image](https://github.com/thomasloven/hass-favicon/assets/9917659/f44d2f49-10e0-4516-af06-7cf518b16870)
Rebooting and report after then ill go to bed

**Comment by TomKranenburg** [comment]
> I do not do this for money or donations. If I did I would have to file taxes for it, and I really don't want to go through the bother. Please use your money for [something better](https://account.nabucasa.com/signup/).
> 
> The path shall be for the directory in which the icons reside. The icon files need to be named as described in the readme.

Thomas you absolute gentleman.

**Comment by IIIdefconIII** [comment]
can you help another thomas out, im still struglging to get it to work, perhaps because this thomas was in coma last year my brain gut shuffled

**Comment by TomKranenburg** [comment]
> can you help another thomas out, im still struglging to get it to work, perhaps because this thomas was in coma last year my brain gut shuffled

Then home automation sounds amazing for you.

So, I did install it. And it does work for me. The part that is infuriating is that you seem to have done everything right from my perspective. The same as I did.

Could you try clicking "refresh" on the home assistant web page while holding shift? This forces it to clear the cache. That's the only other thing that I did.

**Comment by IIIdefconIII** [comment]
> > can you help another thomas out, im still struglging to get it to work, perhaps because this thomas was in coma last year my brain gut shuffled
> 
> Then home automation sounds amazing for you.
> 
> So, I did install it. And it does work for me. The part that is infuriating is that you seem to have done everything right from my perspective. The same as I did.
> 
> Could you try clicking "refresh" on the home assistant web page while holding shift? This forces it to clear the cache. That's the only other thing that I did.

Hi thanks for you reply, yeah i did that, CTRL +R, CTRL+ F5, clear cache and cookies and even tried incognito mode + another browser like firefox.

restarted ha multiple times because im into migrating my old homepage to homeassistant aswell i think its just bad luck for me xD

**Comment by TomKranenburg** [comment]
Ahhh well. Worth a shot.

Now, could you press F12 for me. And then navigate to the "Network" tab:

![image](https://github.com/thomasloven/hass-favicon/assets/10760232/a9e87556-2366-44fa-b147-254bdd0cdb90)

Then click the clear button:

![image](https://github.com/thomasloven/hass-favicon/assets/10760232/60f91529-f0ee-4e25-b274-06de2f5922a1)

Then refresh the page again.

Now from the list you should be able to find favicon.ico being loaded. Can you tell me what path it has? You can see my example here:

![image](https://github.com/thomasloven/hass-favicon/assets/10760232/4ee0d0a7-6743-47c8-9457-a5819aa64a14)

Also might be worth taking a quick look in the console tab as well to see if there are any errors:

![image](https://github.com/thomasloven/hass-favicon/assets/10760232/cd6b7308-50db-4cdc-ab2c-e24ce07b7802)

**Comment by IIIdefconIII** [comment]
***@***.***

Hi, is did all the steps you mentioned,
The favicon.ico here in the debug windows in network shows me a external url do, that might be the problem.
Ill try checking the setting itself again and report back

Van: TomKranenburg ***@***.***>
Verzonden: vrijdag 1 maart 2024 15:56
Aan: thomasloven/hass-favicon ***@***.***>
CC: Thomas van Dalen ***@***.***>; Author ***@***.***>
Onderwerp: Re: [thomasloven/hass-favicon] myne favicon doesnt change or load (Issue #32)


Ahhh well. Worth a shot.

Now, could you press F12 for me. And then navigate to the "Network" tab:

image.png (view on web)<https://github.com/thomasloven/hass-favicon/assets/10760232/a9e87556-2366-44fa-b147-254bdd0cdb90>

Then click the clear button:

image.png (view on web)<https://github.com/thomasloven/hass-favicon/assets/10760232/60f91529-f0ee-4e25-b274-06de2f5922a1>

Then refresh the page again.

Now from the list you should be able to find favicon.ico being loaded. Can you tell me what path it has? You can see my example here:

image.png (view on web)<https://github.com/thomasloven/hass-favicon/assets/10760232/4ee0d0a7-6743-47c8-9457-a5819aa64a14>

Also might be worth taking a quick look in the console tab as well to see if there are any errors:

image.png (view on web)<https://github.com/thomasloven/hass-favicon/assets/10760232/cd6b7308-50db-4cdc-ab2c-e24ce07b7802>

**Comment by IIIdefconIII** [comment]
![image](https://github.com/thomasloven/hass-favicon/assets/9917659/3df99240-05f9-4684-a8d6-e1c4feff6eb7)

**Comment by IIIdefconIII** [comment]
![image](https://github.com/thomasloven/hass-favicon/assets/9917659/1f88d793-2cde-4445-837e-ae2d2bef5dba)

**Comment by IIIdefconIII** [comment]
change the title to Skynet2 but also doesnt change in the titblebar

**Comment by TomKranenburg** [comment]
I can see there for some reason the HAC extension isn't working. You're still loading this old one. Weird.

You're editing http.yaml there I see. The favicon entry is in your configuration.yaml as well? I actually used the integration method. Did you try that? I didn't actually edit a yaml to get this working for once.

**Comment by IIIdefconIII** [comment]
hi yes i have a kinda complex setup ill try to explain:

Configuration.yaml:
![image](https://github.com/thomasloven/hass-favicon/assets/9917659/ae9ff126-b82c-4082-910e-e2f6ef8bb13a)
![image](https://github.com/thomasloven/hass-favicon/assets/9917659/3edb8ed3-af5e-4986-b476-dd16c140a269)
![image](https://github.com/thomasloven/hass-favicon/assets/9917659/00b2af7b-1e3f-4047-bee7-4929c2b22e60)
![image](https://github.com/thomasloven/hass-favicon/assets/9917659/7f756068-4d4a-4c58-bff7-e465eb58a575)

all other lose yaml files in those subdirectorys all work so this should work aswell

**Comment by TomKranenburg** [comment]
Can you try the integration?

Example:

![image](https://github.com/thomasloven/hass-favicon/assets/10760232/c44c7d24-9c5c-4288-91be-ec97c75859d7)

Might help.

**Comment by IIIdefconIII** [comment]
![image](https://github.com/thomasloven/hass-favicon/assets/9917659/76fe1bf1-e2b3-427a-8310-f3f6bf089a0e)
Its there

![image](https://github.com/thomasloven/hass-favicon/assets/9917659/5c44d484-cc49-48fe-bfa2-f39a27962a38)

![image](https://github.com/thomasloven/hass-favicon/assets/9917659/858cfccb-9e9d-419d-854a-c95876d289a8)

I will change the title here and see what happens, ill report back

**Comment by IIIdefconIII** [comment]
Ok so the title got updated after a restart

![image](https://github.com/thomasloven/hass-favicon/assets/9917659/577630b4-99c2-4b57-9a73-7b52f37e1a73)

but the icon is still giving a big finger, int he middle of the hand xD, ill try it later on another browser because i do know chrome is always beeing a .....BEEEP about favicons cache. report back alter need to do some groceries now. Thanks again im 1 step closer

**Comment by TomKranenburg** [comment]
Yes that's ok. I think your icon path just needs to be adjusted. Here's mine.

![image](https://github.com/thomasloven/hass-favicon/assets/10760232/afcc95ec-63b1-49a3-9fa4-f73053475b10)

Make sure your icon is called "favicon.ico" as well. It will automatically load it. A PNG I don't think will work. I'm not sure.

**Comment by IIIdefconIII** [comment]
Restarting Now:
Change the page title back to SkyNet
Adjusted the icon path to /local/favicons/

have the favicon.ico in that folder:
![image](https://github.com/thomasloven/hass-favicon/assets/9917659/3954d436-3e21-4b12-85e3-be54f618ab33)
report back in a few min

**Comment by IIIdefconIII** [comment]
it may sounds scary,

but i love you! thank you so much!

![image](https://github.com/thomasloven/hass-favicon/assets/9917659/343221e9-0fa1-4815-b355-19fe109d4a5e)

**Comment by IIIdefconIII** [comment]
Everything worked out, I also did a pull on the readme. 😉 thanks a lot for your patient and documentation and help, I really appreciate it Thomas from another Thomas here.

😃



Van: TomKranenburg ***@***.***>
Verzonden: vrijdag 1 maart 2024 16:53
Aan: thomasloven/hass-favicon ***@***.***>
CC: Thomas van Dalen ***@***.***>; Author ***@***.***>
Onderwerp: Re: [thomasloven/hass-favicon] myne favicon doesnt change or load (Issue #32)


Yes that's ok. I think your icon path just needs to be adjusted. Here's mine.

image.png (view on web)<https://github.com/thomasloven/hass-favicon/assets/10760232/afcc95ec-63b1-49a3-9fa4-f73053475b10>

Make sure your icon is called "favicon.ico" as well. It will automatically load it. A PNG I don't think will work. I'm not sure.

**Comment by TomKranenburg** [comment]
> it may sounds scary,
> 
> but i love you! thank you so much!
> 
> ![image](https://private-user-images.githubusercontent.com/9917659/309331589-343221e9-0fa1-4815-b355-19fe109d4a5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMTQwMTIsIm5iZiI6MTcwOTMxMzcxMiwicGF0aCI6Ii85OTE3NjU5LzMwOTMzMTU4OS0zNDMyMjFlOS0wZmExLTQ4MTUtYjM1NS0xOWZlMTA5ZDRhNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMTcyMTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmJmNzU5NDA4OWQwZDhjMDZmNzY1MzM2NDNhNDQ2YmQ0ODk4OGFjOGE3ZTM4NGIxYWExMDRmYjYwNGQxNTQ1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.byKyx80JgMQOD0DZ9qrOD24XfyXoOQWGHneEU5M5s4Q) external url know also works: (the SSL in the bookmartks bar) ![image](https://private-user-images.githubusercontent.com/9917659/309331721-8e855e3b-bebd-4ac5-a50c-0129b02057a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMTQwMTIsIm5iZiI6MTcwOTMxMzcxMiwicGF0aCI6Ii85OTE3NjU5LzMwOTMzMTcyMS04ZTg1NWUzYi1iZWJkLTRhYzUtYTUwYy0wMTI5YjAyMDU3YTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMTcyMTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2JlM2Y2ZGU5YTE4NmVkZDI0OWZkNjNiMzA2YzBhYjM4NThkMWQ0MWE4ZGY1ZGM1NmUyNTY3YWMxZThhZjkxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Dv6A_1tH7N5TlwUhPoaD5Ii0wQwh1LKxrdnBVn6QVTk)

My pleasure don't worry about it. 

Have a good weekend my friend.

**Comment by IIIdefconIII** [comment]
> > it may sounds scary,
> > but i love you! thank you so much!
> > ![image](https://private-user-images.githubusercontent.com/9917659/309331589-343221e9-0fa1-4815-b355-19fe109d4a5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMTQwMTIsIm5iZiI6MTcwOTMxMzcxMiwicGF0aCI6Ii85OTE3NjU5LzMwOTMzMTU4OS0zNDMyMjFlOS0wZmExLTQ4MTUtYjM1NS0xOWZlMTA5ZDRhNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMTcyMTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmJmNzU5NDA4OWQwZDhjMDZmNzY1MzM2NDNhNDQ2YmQ0ODk4OGFjOGE3ZTM4NGIxYWExMDRmYjYwNGQxNTQ1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.byKyx80JgMQOD0DZ9qrOD24XfyXoOQWGHneEU5M5s4Q) external url know also works: (the SSL in the bookmartks bar) ![image](https://private-user-images.githubusercontent.com/9917659/309331721-8e855e3b-bebd-4ac5-a50c-0129b02057a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMTQwMTIsIm5iZiI6MTcwOTMxMzcxMiwicGF0aCI6Ii85OTE3NjU5LzMwOTMzMTcyMS04ZTg1NWUzYi1iZWJkLTRhYzUtYTUwYy0wMTI5YjAyMDU3YTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMTcyMTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2JlM2Y2ZGU5YTE4NmVkZDI0OWZkNjNiMzA2YzBhYjM4NThkMWQ0MWE4ZGY1ZGM1NmUyNTY3YWMxZThhZjkxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Dv6A_1tH7N5TlwUhPoaD5Ii0wQwh1LKxrdnBVn6QVTk)
> 
> My pleasure don't worry about it.
> 
> Have a good weekend my friend.

last qution do can you remove those last 1 picture just because my ssl url is in it xD

![image](https://github.com/thomasloven/hass-favicon/assets/9917659/1b623981-f479-4f8e-b38e-301bc6d164d5)

**Comment by IIIdefconIII** [comment]
#close thanks lot for the help @thomasloven its all perfect now! GB you and w emight talk again ever :)
