### ISSUE TITLE
Browser Icon Doesn't Change

### ISSUE THREAD

**Issue by frr032** [thomasloven/hass-favicon#34]
I cannot seem to get the browser tab icon to change.  The title does.  I get an error in the log that I think says the Icon path is not found.  I have tried several variants of the path, and none work.  I have cleared the browser cashed files and images each time.  Restarted HA many times as well.

See snips and log below.

What am I doing incorrectly?

Thanks
FRR

![image](https://github.com/thomasloven/hass-favicon/assets/110492786/8cd28150-6c25-43ab-99db-44ff2468c5be)

![image](https://github.com/thomasloven/hass-favicon/assets/110492786/9f64bc1e-7605-4121-9378-81e61523b7d9)

**Error Log**
This error originated from a custom integration.

Logger: custom_components.favicon.config_flow
Source: custom_components/favicon/config_flow.py:45
Integration: Favicon (documentation)
First occurred: 9:02:39 PM (8 occurrences)
Last logged: 9:14:32 PM

{'title': 'Dev', 'icon_path': '/config/www/favicons/favicon'}
{'title': 'Dev', 'icon_path': '/config/www/favicons/dev'}
{'title': 'Dev', 'icon_path': '/config/www/favicons/dev.ico'}
{'title': 'Dev', 'icon_path': 'config/www/favicons/dev'}
{'title': 'Dev', 'icon_path': 'local/favicons/dev'}

**HA Version**
Core
2024.2.5
Supervisor
2024.02.1
Operating System
12.0
Frontend
20240207.1

**Comment by frr032** [comment]
Any suggestions?

**Comment by frr032** [comment]
Hello?  Should I be posting this issue somewhere else?

**Comment by thomasloven** [comment]
Your icon files do not have the names the readme says they must have.
