### ISSUE TITLE
no integration favicon

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/hass-favicon#6]
after having installed the custom component in its correct folder and the icons in the www folder, and having restarted the HA instance, there is no integration favicon in the integrations list.

not sure what to post since I don't have errors.

ha 103.4 rpi3 hassio

**Comment by thomasloven** [comment]
Check if you have an integration with no name, just an empty entry in the list.
If you do, make sure you also got the hidden directory `custom_components/favicon/.translations/` in the right place.

**Comment by Mariusthvdb** [comment]
i have all the files in the correct position:
![Schermafbeelding 2019-12-23 om 12 08 56](https://user-images.githubusercontent.com/33354141/71359206-ede34d80-258b-11ea-9517-cb9e9c537caa.jpg)
and
![Schermafbeelding 2019-12-23 om 12 09 07](https://user-images.githubusercontent.com/33354141/71359211-f5a2f200-258b-11ea-86bb-1b5be50e206a.jpg)

and no, there was no empty slot in the list, as far as I could see.

For the sake of it I tried to type fav in the search box and this is what popped up:

![Schermafbeelding 2019-12-23 om 12 09 27](https://user-images.githubusercontent.com/33354141/71359249-1703de00-258c-11ea-8efd-3536c1fa3885.jpg)

I then entered my objective name and path to the icon as in the video

page title: `Ha Z-wave` and icon path `/local/favicons/green`

but nothing  happening unfortunately.

**Comment by thomasloven** [comment]
The same video also shows how the icons folder should look

https://github.com/thomasloven/hass-favicon#about-the-icons

**Comment by Mariusthvdb** [comment]
Ok sorry about that,  missed the dedicated icons...

Added them now via the tool you supplied, and left out the android icons, since I do not use that.

![Schermafbeelding 2019-12-24 om 00 55 10](https://user-images.githubusercontent.com/33354141/71385579-d2f2f680-25e8-11ea-8c72-530ad7348068.jpg)

Still no icon appears. I've adjusted the path to what is described in your text:
`/local/favicons/`

(note that the video points to /local/favicons/green , which got me confused at first, seems a typo?)

**Comment by Mariusthvdb** [comment]
closing this, as I have successfully installed favicon on 3 instances now, the issue above was a combination with Custom Header, and under the attention of the author.
thanks!
